INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (1, '아시아');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (2, '유럽');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (3, '중동');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (4, '아프리카');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (5, '북아메리카');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (6, '남아메리카');
INSERT INTO CONTINENT (CONTINENT_ID, CONTINENT_NAME)
VALUES (7, '오세아니아');

INSERT INTO NATION_INFO (NATION_INFO_ID, CONTINENT_ID, NATION_NAME, INTRODUCE, QUARANTINE_POLICY,
                         IMAGE_URL)
VALUES (1, 1, '대한민국', 'hi', 'hello', 'haha');